/*
 * Copyright (c) 2024, Alibaba Group;
 * Licensed under the Apache License, Version 2.0 (the "License");
 *
 * ---
 * DECOUPLED REPLAY: Independent NS3 replay binary entry point.
 *
 * This binary replays flow files generated by SimAI coupled simulation.
 * It links ONLY against ns3 libraries -- ZERO astra-sim symbols.
 *
 * Build verification: nm scratch_decoupled_replay_main | grep -i simai
 * Must return EMPTY.
 *
 * CLI arguments:
 *   -f, --flow-file      Path to flow file (required)
 *   -t, --topo-dir       Topology directory (e.g., Spectrum-X_128g_...)
 *   -c, --config         SimAI.conf path (default: topo-dir/SimAI.conf)
 *   -o, --fct-output     FCT output file (default: fct.txt)
 *   -s, --stop-time      Simulator stop time in seconds (default: 2000000000)
 *   --verify-dag         Run DAG cycle detection before simulation
 *   --dump-layer-stats   Output per-layer timing statistics JSON
 */

#include "common_types.h"
#include "flow_reader.h"
#include "topology_reader.h"
#include "flow_sender.h"
#include "fct_writer.h"
#include "dep_scheduler.h"

#include <cstring>
#include <iostream>
#include <csignal>

// Global scheduler pointer for signal handler / early exit reporting
static DepScheduler* g_scheduler = nullptr;

// Signal handler for graceful shutdown (reports partial stats)
static void signal_handler(int sig) {
    std::cerr << "\n[DecoupledReplay] Caught signal " << sig
              << ", shutting down..." << std::endl;
    if (g_scheduler) {
        g_scheduler->VerifyCompletion();
        g_scheduler->DumpLayerStats();
    }
    exit(1);
}

int main(int argc, char *argv[]) {
    // Register signal handlers for graceful shutdown
    std::signal(SIGINT, signal_handler);
    std::signal(SIGTERM, signal_handler);

    // Default paths
    std::string topo_dir = "";
    std::string config_path = "";
    std::string flow_file_path = "";
    double sim_stop_time = 2000000000.0;  // effectively no limit
    bool dump_layer_stats = false;
    bool verify_dag = false;

    // Parse CLI arguments
    for (int i = 1; i < argc; i++) {
        std::string arg = argv[i];
        if ((arg == "-t" || arg == "--topo-dir") && i + 1 < argc) {
            topo_dir = argv[++i];
        } else if ((arg == "-c" || arg == "--config") && i + 1 < argc) {
            config_path = argv[++i];
        } else if ((arg == "-f" || arg == "--flow-file") && i + 1 < argc) {
            flow_file_path = argv[++i];
        } else if ((arg == "-o" || arg == "--fct-output") && i + 1 < argc) {
            fct_output_file = argv[++i];
        } else if ((arg == "-s" || arg == "--stop-time") && i + 1 < argc) {
            sim_stop_time = std::stod(argv[++i]);
        } else if (arg == "--verify-dag") {
            verify_dag = true;
        } else if (arg == "--dump-layer-stats") {
            dump_layer_stats = true;
        } else if (arg == "-h" || arg == "--help") {
            std::cout << "Usage: " << argv[0] << " [OPTIONS]\n"
                      << "  -f, --flow-file PATH    Flow file to replay (required)\n"
                      << "  -t, --topo-dir DIR      Topology directory\n"
                      << "  -c, --config PATH       Config file (default: topo-dir/SimAI.conf)\n"
                      << "  -o, --fct-output PATH   FCT output file (default: fct.txt)\n"
                      << "  -s, --stop-time SEC     Simulator stop time (default: 2000000000)\n"
                      << "  --verify-dag            Run DAG cycle detection before simulation\n"
                      << "  --dump-layer-stats      Output per-layer timing statistics\n"
                      << "  -h, --help              Show this help\n";
            return 0;
        }
    }

    if (flow_file_path.empty()) {
        std::cerr << "ERROR: --flow-file is required. Use -h for help." << std::endl;
        return 1;
    }

    // Resolve config and topology paths
    if (config_path.empty()) {
        config_path = topo_dir + "/SimAI.conf";
    }
    std::string topo_xml = topo_dir + "/POD#1.xml";

    // =====================================================================
    // Step 1: Read configuration + apply NS3 defaults
    // =====================================================================
    std::cout << "[DecoupledReplay] Reading configuration..." << std::endl;
    if (!ReadConf(topo_xml, config_path)) {
        std::cerr << "ERROR: ReadConf failed" << std::endl;
        return 1;
    }
    SetConfig();

    // =====================================================================
    // Step 2: Setup NS3 network
    // =====================================================================
    std::cout << "[DecoupledReplay] Setting up network..." << std::endl;
    SetupNetwork(qp_finish, send_finish);

    // =====================================================================
    // Step 3: Load flows from file
    // =====================================================================
    std::cout << "[DecoupledReplay] Loading flows from " << flow_file_path << "..." << std::endl;
    std::vector<FlowFileRecord> flows = LoadFlows(flow_file_path);
    if (flows.empty()) {
        std::cerr << "ERROR: No flows loaded from " << flow_file_path << std::endl;
        return 1;
    }
    std::cout << "[DecoupledReplay] Loaded " << flows.size() << " flows." << std::endl;

    // Log flow distribution
    {
        std::map<int, int> layer_counts;
        for (const auto& f : flows) {
            layer_counts[f.layer_num]++;
        }
        std::cout << "[DecoupledReplay] Flow distribution by layer: ";
        for (const auto& lc : layer_counts) {
            std::cout << "L" << lc.first << "=" << lc.second << " ";
        }
        std::cout << std::endl;
    }

    // =====================================================================
    // Step 4: Init DepScheduler
    // =====================================================================
    DepScheduler scheduler;
    g_scheduler = &scheduler;

    if (!scheduler.Init(flows)) {
        std::cerr << "ERROR: DepScheduler::Init failed" << std::endl;
        return 1;
    }

    // Optional: DAG cycle detection
    if (verify_dag) {
        if (!scheduler.VerifyDAG()) {
            std::cerr << "ERROR: DAG verification failed (cycles detected)" << std::endl;
            return 1;
        }
    }

    // Register the flow-completion callback (links qp_finish → DepScheduler)
    g_on_flow_completed = [](uint32_t flow_id) {
        if (g_scheduler) {
            g_scheduler->OnFlowCompleted(flow_id);
        }
    };

    // =====================================================================
    // Step 5: Schedule initial ready flows
    // =====================================================================
    std::cout << "[DecoupledReplay] Scheduling initial flows..." << std::endl;
    scheduler.ScheduleReadyFlows();

    // =====================================================================
    // Step 6: Run simulation
    // =====================================================================
    std::cout << "[DecoupledReplay] Running simulation (stop_time="
              << sim_stop_time << "s)..." << std::endl;
    fflush(stdout);
    NS_LOG_INFO("Run Simulation.");

    Simulator::Stop(Seconds(sim_stop_time));
    Simulator::Run();

    // =====================================================================
    // Step 7: Verify completion and output stats
    // =====================================================================
    bool all_completed = scheduler.VerifyCompletion();

    if (dump_layer_stats) {
        scheduler.DumpLayerStats();
    }

    if (!all_completed) {
        std::cerr << "[DecoupledReplay] WARNING: Not all flows completed. "
                  << "Increase --stop-time if flows were still in-flight." << std::endl;
    }

    // =====================================================================
    // Step 8: Cleanup
    // =====================================================================
    g_on_flow_completed = nullptr;
    g_scheduler = nullptr;

    Simulator::Destroy();

    std::cout << "[DecoupledReplay] Done. FCT output: " << fct_output_file << std::endl;
    return all_completed ? 0 : 1;
}
