import { create } from 'zustand';
import type {
  WizardStep,
  WorkloadConfig,
  WorkloadLayer,
  RankTable,
  RankRackMap,
  LaunchConfig,
  SimulationStatus,
  EndToEndData,
  ConsoleData,
} from '../types/wizard';
import type { EdgGraph, EdgDiff } from '../types/edg';

interface WizardState {
  // Navigation
  readonly currentStep: WizardStep;
  readonly completedSteps: ReadonlySet<WizardStep>;

  // Workload
  readonly workloadMode: 'preset' | 'custom' | 'upload';
  readonly workloadConfig: WorkloadConfig;
  readonly workloadContent: string;
  readonly workloadLayers: readonly WorkloadLayer[];
  readonly workloadSaved: boolean;
  readonly workloadSavedPath: string;

  // RankTable (auto-generated by EDG page)
  readonly ranktableData: RankTable | null;
  readonly rankRackMap: RankRackMap | null;
  readonly ranktableSaved: boolean;
  readonly ranktableSavedPath: string;

  // Topology
  readonly topologyDir: string;

  // EDG
  readonly edgTaskId: string;
  readonly edgTopologyPath: string;
  readonly edgBaselineGraph: EdgGraph | null;
  readonly edgAdjustedGraph: EdgGraph | null;
  readonly edgDiff: EdgDiff | null;
  readonly edgSkipped: boolean;

  // Launch
  readonly launchConfig: LaunchConfig;
  readonly activePid: number | null;
  readonly simulationStatus: SimulationStatus;

  // Results
  readonly resultPrefix: string;
  readonly endtoendData: EndToEndData | null;
  readonly consoleData: ConsoleData | null;

  // Actions
  setCurrentStep: (step: WizardStep) => void;
  completeStep: (step: WizardStep) => void;
  goToStep: (step: WizardStep) => void;

  setWorkloadMode: (mode: 'preset' | 'custom' | 'upload') => void;
  setWorkloadConfig: (config: WorkloadConfig) => void;
  setWorkloadContent: (content: string, layers: readonly WorkloadLayer[]) => void;
  setWorkloadSaved: (saved: boolean, path?: string) => void;
  setWorkloadSavedPath: (path: string) => void;

  setRanktableData: (data: RankTable, map: RankRackMap) => void;
  setRanktableSaved: (saved: boolean) => void;
  setRanktableSavedPath: (path: string) => void;

  setTopologyDir: (dir: string) => void;

  setEdgTaskId: (id: string) => void;
  setEdgTopologyPath: (path: string) => void;
  setEdgBaselineGraph: (graph: EdgGraph | null) => void;
  setEdgAdjustedGraph: (graph: EdgGraph | null) => void;
  setEdgDiff: (diff: EdgDiff | null) => void;
  setEdgSkipped: (skipped: boolean) => void;

  setLaunchConfig: (config: Partial<LaunchConfig>) => void;
  setActivePid: (pid: number | null) => void;
  setSimulationStatus: (status: SimulationStatus) => void;
  setResultPrefix: (prefix: string) => void;

  setEndtoendData: (data: EndToEndData | null) => void;
  setConsoleData: (data: ConsoleData | null) => void;

  reset: () => void;
}

const DEFAULT_WORKLOAD_CONFIG: WorkloadConfig = {
  model_size: 'LLaMA-7B',
  tp_size: 8,
  dp_size: 1,
  pp_size: 1,
  ep_size: 1,
  all_gpus: 8,
  ga: 8,
  vpp: 1,
};

const DEFAULT_LAUNCH_CONFIG: LaunchConfig = {
  collectiveMode: 'nccl',
  mode: 'analytical',
  workloadPath: '',
  ranktablePath: '',
  topologyPath: '',
  threads: 8,
  envVars: {},
  oxcUrl: '',
  oxcAlgo: '',
  tpOverlap: 0,
  dpOverlap: 0,
  epOverlap: 0,
  ppOverlap: 1,
  intraBw: 0,
  nicBw: 0,
  npuType: 'A3',
  nicType: 'cx7',
};

const INITIAL_STATE = {
  currentStep: 'workload' as WizardStep,
  completedSteps: new Set<WizardStep>(),
  workloadMode: 'preset' as const,
  workloadConfig: DEFAULT_WORKLOAD_CONFIG,
  workloadContent: '',
  workloadLayers: [] as readonly WorkloadLayer[],
  workloadSaved: false,
  workloadSavedPath: '',
  ranktableData: null,
  rankRackMap: null,
  ranktableSaved: false,
  ranktableSavedPath: '',
  topologyDir: '',
  edgTaskId: 'T001',
  edgTopologyPath: '',
  edgBaselineGraph: null as EdgGraph | null,
  edgAdjustedGraph: null as EdgGraph | null,
  edgDiff: null as EdgDiff | null,
  edgSkipped: false,
  launchConfig: DEFAULT_LAUNCH_CONFIG,
  activePid: null,
  simulationStatus: 'idle' as SimulationStatus,
  resultPrefix: '',
  endtoendData: null,
  consoleData: null,
};

export const useWizardStore = create<WizardState>((set) => ({
  ...INITIAL_STATE,

  setCurrentStep: (step) => set({ currentStep: step }),

  completeStep: (step) =>
    set((state) => ({
      completedSteps: new Set([...state.completedSteps, step]),
    })),

  goToStep: (step) => set({ currentStep: step }),

  setWorkloadMode: (mode) => set({ workloadMode: mode }),

  setWorkloadConfig: (config) => set({ workloadConfig: config }),

  setWorkloadContent: (content, layers) =>
    set({ workloadContent: content, workloadLayers: layers }),

  setWorkloadSaved: (saved, path) => set({ workloadSaved: saved, workloadSavedPath: path ?? '' }),
  setWorkloadSavedPath: (path) => set({ workloadSavedPath: path }),

  setRanktableData: (data, map) =>
    set({ ranktableData: data, rankRackMap: map }),

  setRanktableSaved: (saved) => set({ ranktableSaved: saved }),
  setRanktableSavedPath: (path) => set({ ranktableSavedPath: path }),

  setTopologyDir: (dir) => set({ topologyDir: dir }),

  setEdgTaskId: (id) => set({ edgTaskId: id }),
  setEdgTopologyPath: (path) => set({ edgTopologyPath: path }),
  setEdgBaselineGraph: (graph) => set({ edgBaselineGraph: graph }),
  setEdgAdjustedGraph: (graph) => set({ edgAdjustedGraph: graph }),
  setEdgDiff: (diff) => set({ edgDiff: diff }),
  setEdgSkipped: (skipped) => set({ edgSkipped: skipped }),

  setLaunchConfig: (partial) =>
    set((state) => ({
      launchConfig: { ...state.launchConfig, ...partial },
    })),

  setActivePid: (pid) => set({ activePid: pid }),

  setSimulationStatus: (status) => set({ simulationStatus: status }),

  setResultPrefix: (prefix) => set({ resultPrefix: prefix }),

  setEndtoendData: (data) => set({ endtoendData: data }),

  setConsoleData: (data) => set({ consoleData: data }),

  reset: () => set({ ...INITIAL_STATE, completedSteps: new Set<WizardStep>() }),
}));
